language: cpp
sudo: false
notifications:
  email: false

# Use Linux unless specified otherwise
os: linux
dist: bionic

matrix:
  include:
    ##########################################################################
    # Clang on Linux
    ##########################################################################
    # Clang 7.0
    - env: COMPILER=clang++-7 BUILD_TYPE=Debug USE_CXX_STANDARD=17
      addons: &clang70
        apt:
          packages:
            - clang-7
            - g++-7
            - cppcheck
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-7


    ##########################################################################
    # GCC on Linux
    ##########################################################################
    # GCC 7
    - env: COMPILER=g++-7 BUILD_TYPE=Debug USE_CXX_STANDARD=17
      addons: &gcc7
        apt:
          packages:
            - g++-7
            - cppcheck
          sources:
            - ubuntu-toolchain-r-test

before_install:
    - git submodule update --init --recursive

script:
     - mkdir -p build
     - cd build
     - cmake ..
     - make

